name: Gitlab mirror

# Controls when the action will run. 
on: [push, create, delete, workflow_dispatch]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Mirroring Repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          # SSH private key for ssh connection to the target repository
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
          # Target url
          target_repo_url: git@github.com:ivido/hapi-fhir.git
